/* Bendheim family numbers — data file.
 *
 * Edit by hand: add, correct or remove a line below. One person per line.
 * A number is the parent's number plus a dot and the child's position among
 * their children; a spouse is the member's number plus S (S2 for a second
 * marriage, SD for a former one).
 *
 * Keep the commas, the quotes and the square brackets exactly as they are.
 * The app checks this file when it loads and tells you if a line is malformed,
 * duplicated, or hangs off somebody who is not listed.
 *
 * Names and structure come from "Names of Bendheim Family Josh.xlsx", sheet Data.
 * An optional "alt" is a second name that search will match but the app never
 * shows — the formal name from the genealogy site. Add or edit it freely.
 */
window.FAMILY_DATA = {
  "root": "2.1.2",
  "root_name": "Opa Charlie Bendheim",
  "people": [
    {"pid": "2.1.2",               "name": "Opa Charlie Bendheim", "alt": "Charles Henry Bendheim"},
    {"pid": "2.1.2S",              "name": "Oma Els Bendheim", "alt": "Els (Salomon) Bendheim"},
    {"pid": "2.1.2.1",             "name": "Judi Guedalia", "alt": "Judith Sandra (Bendheim) Guedalia"},
    {"pid": "2.1.2.1S",            "name": "Harris Guedalia"},
    {"pid": "2.1.2.1.1",           "name": "Allison (Guedalia) Kupietzky", "alt": "Allison Siffre (Guedalia) Kupietzky"},
    {"pid": "2.1.2.1.1S",          "name": "Ari Kupietzky"},
    {"pid": "2.1.2.1.1.1",         "name": "Eitan Kupietzky", "alt": "Eitan Yaacov Zvi Kupietzky"},
    {"pid": "2.1.2.1.1.1S",        "name": "Miriam (Gershon) Kupietzky", "alt": "Miriam Hasha Gershon Kupietzky"},
    {"pid": "2.1.2.1.1.1.1",       "name": "Lavi Kupietzky", "alt": "Yehuda Lavi Kupietzky"},
    {"pid": "2.1.2.1.1.1.2",       "name": "Benaya Kupietzky", "alt": "Benaya Eliyahu Kupietzky"},
    {"pid": "2.1.2.1.1.1.3",       "name": "Akiva Kupietzky", "alt": "Akiva Yerucham Kupietzky"},
    {"pid": "2.1.2.1.1.1.4",       "name": "Choni Kupietzky"},
    {"pid": "2.1.2.1.1.1.5",       "name": "Petachya Kupietzky"},
    {"pid": "2.1.2.1.1.1.6",       "name": "Reah Mevasseret Kupietzky"},
    {"pid": "2.1.2.1.1.1.7",       "name": "Ziv Adin Kupietzky"},
    {"pid": "2.1.2.1.1.1.8",       "name": "Hadar Yemima Kupietzky"},
    {"pid": "2.1.2.1.1.2",         "name": "Gilat (Kupietzky) Sacks", "alt": "Gail Chaya Kupietzky"},
    {"pid": "2.1.2.1.1.2S",        "name": "Asher Sacks", "alt": "Asher Yehuda Sacks"},
    {"pid": "2.1.2.1.1.2.1",       "name": "Itai Sacks"},
    {"pid": "2.1.2.1.1.2.2",       "name": "Amichai Sacks"},
    {"pid": "2.1.2.1.1.2.3",       "name": "Nerya Sacks"},
    {"pid": "2.1.2.1.1.2.4",       "name": "Shir Lia Zipora Sacks"},
    {"pid": "2.1.2.1.1.2.5",       "name": "Elisha David Sacks"},
    {"pid": "2.1.2.1.1.3",         "name": "Chanan Kupietzky", "alt": "Chanan Abraham Kupietzky"},
    {"pid": "2.1.2.1.1.3S",        "name": "Sophie (Taub) Kupietzky"},
    {"pid": "2.1.2.1.1.3.1",       "name": "Paula Esther-Shaya Kupietzky"},
    {"pid": "2.1.2.1.1.3.2",       "name": "Shilo Judi Kupietzky"},
    {"pid": "2.1.2.1.1.3.3",       "name": "Sinai Ariel Kupietzky"},
    {"pid": "2.1.2.1.1.3.4",       "name": "Dagan Elias Kupietzky"},
    {"pid": "2.1.2.1.1.3.5",       "name": "Odelle Sheba Kupietzky"},
    {"pid": "2.1.2.1.1.4",         "name": "Gidon Kupietzky", "alt": "Gidon Yair Kupietzky"},
    {"pid": "2.1.2.1.1.4S",        "name": "Shoshi (Taragin) Kupietzky"},
    {"pid": "2.1.2.1.1.4.1",       "name": "Chana Ayala Kupietzky"},
    {"pid": "2.1.2.1.1.4.2",       "name": "Ashira Batya Kupietzky"},
    {"pid": "2.1.2.1.1.4.3",       "name": "Emanuel Yisrael Kupietzky"},
    {"pid": "2.1.2.1.1.4.4",       "name": "Yosef Chaim Kupietzky"},
    {"pid": "2.1.2.1.1.5",         "name": "Daniella (Kupietzky) Brounstein", "alt": "Daniella Nessia Kupietzky"},
    {"pid": "2.1.2.1.1.5S",        "name": "Gilad Brounstein"},
    {"pid": "2.1.2.1.1.5.1",       "name": "Odeya Tova Tzofia Brounstein"},
    {"pid": "2.1.2.1.1.5.2",       "name": "Matanya Brounstein"},
    {"pid": "2.1.2.1.1.5.3",       "name": "Hod Yosef Brounstein"},
    {"pid": "2.1.2.1.1.5.4",       "name": "Argaman Aminadav Yerucham Brounstein"},
    {"pid": "2.1.2.1.1.6",         "name": "Matanel Kupietzky", "alt": "Matanel Charles Kupietzky"},
    {"pid": "2.1.2.1.1.6S",        "name": "Talia (Seifras) Kupietzky"},
    {"pid": "2.1.2.1.1.6.1",       "name": "Nediva Rivka Kupietzky"},
    {"pid": "2.1.2.1.1.6.2",       "name": "Yardena Tzippora Kupietzky"},
    {"pid": "2.1.2.1.1.7",         "name": "Binyamin Kupietzky", "alt": "Binyamin Zefania Kupietzky"},
    {"pid": "2.1.2.1.1.7S",        "name": "Zaria (Strauss) Kupietzky", "alt": "Zaria Yardenna Strauss"},
    {"pid": "2.1.2.1.1.7.1",       "name": "Lior Shalom Kupietzky"},
    {"pid": "2.1.2.1.2",           "name": "Jacob Guedalia", "alt": "Jacob Leon Guedalia"},
    {"pid": "2.1.2.1.2S",          "name": "Milana (Sobol) Guedalia"},
    {"pid": "2.1.2.1.2.1",         "name": "Fiona Guedalia", "alt": "Fiona Dorothea Guedalia"},
    {"pid": "2.1.2.1.2.2",         "name": "Stephanie Guedalia"},
    {"pid": "2.1.2.1.2.3",         "name": "Chloe Guedalia"},
    {"pid": "2.1.2.1.2.3S",        "name": "Scott Gershon"},
    {"pid": "2.1.2.1.2.4",         "name": "Charlotte Guedalia", "alt": "Charlotte Paula Guedalia"},
    {"pid": "2.1.2.1.2.5",         "name": "Joey Guedalia", "alt": "Joseph Leon Guedalia"},
    {"pid": "2.1.2.1.2.5S",        "name": "Molly (Kramer) Guedalia"},
    {"pid": "2.1.2.1.2.6",         "name": "Roman Guedalia"},
    {"pid": "2.1.2.1.2.7",         "name": "Noa Alexandra Elisheva Guedalia"},
    {"pid": "2.1.2.1.3",           "name": "David Guedalia", "alt": "Issac David Guedalia"},
    {"pid": "2.1.2.1.3S",          "name": "Dina (Zuckerbrot) Guedalia", "alt": "Dina Leah (Zucherbrod) Guedalia"},
    {"pid": "2.1.2.1.3.1",         "name": "Shira Ephrat", "alt": "Shira Gabriella Guedalia"},
    {"pid": "2.1.2.1.3.1S",        "name": "Yonatan Ephrat"},
    {"pid": "2.1.2.1.3.1.1",       "name": "Liam Dor Ephrat"},
    {"pid": "2.1.2.1.3.1.2",       "name": "Adin Yehuda Ephrat"},
    {"pid": "2.1.2.1.3.1.3",       "name": "Ella Ruth Ephrat"},
    {"pid": "2.1.2.1.3.2",         "name": "Asher Guedalia", "alt": "Asher Raphael Guedalia"},
    {"pid": "2.1.2.1.3.2S",        "name": "Noor (van Dam) Guedalia"},
    {"pid": "2.1.2.1.3.2.1",       "name": "Carmel Esther Guedalia"},
    {"pid": "2.1.2.1.3.2.2",       "name": "Ayala Sara Guedalia"},
    {"pid": "2.1.2.1.3.2.3",       "name": "Rachel Angel Guedalia"},
    {"pid": "2.1.2.1.3.3",         "name": "Yael (Guedalia) Ben Shimol", "alt": "Yael Aura Guedalia"},
    {"pid": "2.1.2.1.3.3S",        "name": "Yedidya Ben Shimol"},
    {"pid": "2.1.2.1.3.3.1",       "name": "Ariel Tuvia Ben Shimol"},
    {"pid": "2.1.2.1.3.3.2",       "name": "Eliyahu Malachi Ben Shimol"},
    {"pid": "2.1.2.1.3.4",         "name": "Charlie Guedalia", "alt": "Charles Michael Guedalia"},
    {"pid": "2.1.2.1.3.4S",        "name": "Revital (Guberman) Guedalia"},
    {"pid": "2.1.2.1.3.4.1",       "name": "Ya'er Yosef Guedalia"},
    {"pid": "2.1.2.1.3.5",         "name": "Yosef Guedalia", "alt": "Yosef Melachi Guedalia"},
    {"pid": "2.1.2.1.3.5S",        "name": "Senai (Weglein) Guedalia"},
    {"pid": "2.1.2.1.3.6",         "name": "Esther Sarah (Guedalia) Mantel"},
    {"pid": "2.1.2.1.3.6S",        "name": "Yair Mantel"},
    {"pid": "2.1.2.1.3.7",         "name": "Elisheva Guedalia"},
    {"pid": "2.1.2.1.4",           "name": "Josh Guedalia", "alt": "Joshua Siegfried Guedalia"},
    {"pid": "2.1.2.1.4S",          "name": "Esti (Weisz) Guedalia", "alt": "Esther Chava (Weisz) Guedalia"},
    {"pid": "2.1.2.1.4.1",         "name": "Efrat (Guedalia) Friedman", "alt": "Efrat Tehila Guedalia"},
    {"pid": "2.1.2.1.4.1S",        "name": "Aryeh Friedman"},
    {"pid": "2.1.2.1.4.1.1",       "name": "Gavriel Tzvi Friedman"},
    {"pid": "2.1.2.1.4.1.2",       "name": "Eliora Rivka Friedman"},
    {"pid": "2.1.2.1.4.1.3",       "name": "Yosef Yehoshua Friedman"},
    {"pid": "2.1.2.1.4.2",         "name": "Avigail (Guedalia) Corn", "alt": "Abigail Hodiya Guedalia"},
    {"pid": "2.1.2.1.4.2S",        "name": "Chesky Corn"},
    {"pid": "2.1.2.1.4.2.1",       "name": "Ariel Yosef Chai Corn"},
    {"pid": "2.1.2.1.4.2.2",       "name": "Amitai Malachi Corn"},
    {"pid": "2.1.2.1.4.2.3",       "name": "Eden Chana Corn"},
    {"pid": "2.1.2.1.4.3",         "name": "Rina (Guedalia) Gelband", "alt": "Rina Guedalia"},
    {"pid": "2.1.2.1.4.3S",        "name": "Yoni Gelband"},
    {"pid": "2.1.2.1.4.3.1",       "name": "Mia Sara Gelband"},
    {"pid": "2.1.2.1.4.3.2",       "name": "Yael Rebecca Gelband"},
    {"pid": "2.1.2.1.4.3.3",       "name": "Yair Malachi Gelband"},
    {"pid": "2.1.2.1.4.4",         "name": "Hagai Guedalia", "alt": "Hagai Jacob Guedalia"},
    {"pid": "2.1.2.1.4.4S",        "name": "Orlee (Levin) Guedalia"},
    {"pid": "2.1.2.1.4.4.1",       "name": "Yosef Tzuri Guedalia"},
    {"pid": "2.1.2.1.4.4.2",       "name": "Benaya Yakir Chen Guedalia"},
    {"pid": "2.1.2.1.4.5",         "name": "Yishai Guedalia"},
    {"pid": "2.1.2.1.4.6",         "name": "Yoav Guedalia", "alt": "Yoav Chaim Guedalia"},
    {"pid": "2.1.2.1.4.7",         "name": "Ayelet Guedalia"},
    {"pid": "2.1.2.1.4.8",         "name": "Judah Guedalia"},
    {"pid": "2.1.2.1.4.9",         "name": "Talia Guedalia"},
    {"pid": "2.1.2.2",             "name": "Jack Bendheim", "alt": "Jack Clifford Bendheim"},
    {"pid": "2.1.2.2S",            "name": "Giti (Butler) Bendheim", "alt": "Gail {Giti} Aliza (Butler) Bendheim"},
    {"pid": "2.1.2.2.1",           "name": "Yonina (Bendheim) Jacobson", "alt": "Yonina Michal (Bendheim) Jacobson"},
    {"pid": "2.1.2.2.1S",          "name": "Zev Jacobson"},
    {"pid": "2.1.2.2.1.1",         "name": "Tali (Jacobson) Koschitsky", "alt": "Avital Meirav Jacobson"},
    {"pid": "2.1.2.2.1.1S",        "name": "Yekutiel Koschitsky"},
    {"pid": "2.1.2.2.1.1.1",       "name": "Itai Yisrael Koschitsky"},
    {"pid": "2.1.2.2.1.1.2",       "name": "Noam Koschitsky"},
    {"pid": "2.1.2.2.1.2",         "name": "Ayelet (Jacobson) Buchine", "alt": "Ayelet Rachel Jacobson"},
    {"pid": "2.1.2.2.1.2S",        "name": "Isaac Buchine"},
    {"pid": "2.1.2.2.1.2.1",       "name": "Ilan Rafael Buchine"},
    {"pid": "2.1.2.2.1.3",         "name": "Anat (Jacobson) Haims", "alt": "Anat Abigail Jacobson"},
    {"pid": "2.1.2.2.1.3S",        "name": "Alex Haims"},
    {"pid": "2.1.2.2.1.3.1",       "name": "Michael Ayden Haims"},
    {"pid": "2.1.2.2.1.4",         "name": "Ephraim Jacobson", "alt": "Ephraim Isaiah Jacobson"},
    {"pid": "2.1.2.2.1.4S",        "name": "Ma'ayan (Schwartz) Jacobson", "alt": "Ma'ayan Ohr Schwartz"},
    {"pid": "2.1.2.2.1.5",         "name": "Azi Jacobson", "alt": "Charles Azariah \"Azi\" Jacobson"},
    {"pid": "2.1.2.2.1.6",         "name": "Sam Raanan Jacobson", "alt": "Samuel Raanan Jacobson"},
    {"pid": "2.1.2.2.1.7",         "name": "Hila Jacobson", "alt": "Hila Zadie Jacobson"},
    {"pid": "2.1.2.2.2",           "name": "Dani Bendheim", "alt": "Daniel Moshe Bendheim"},
    {"pid": "2.1.2.2.2S",          "name": "Shifra (Drazin) Bendheim"},
    {"pid": "2.1.2.2.2.1",         "name": "Charlie Bendheim", "alt": "Charles Bendheim"},
    {"pid": "2.1.2.2.2.1S",        "name": "Yakirah (Rosen) Bendheim"},
    {"pid": "2.1.2.2.2.2",         "name": "Sam Bendheim", "alt": "Yisrael Gavriel Bendheim"},
    {"pid": "2.1.2.2.2.3",         "name": "Leebee Bendheim"},
    {"pid": "2.1.2.2.2.4",         "name": "Arielle Bendheim"},
    {"pid": "2.1.2.2.2.5",         "name": "Sophie Bendheim"},
    {"pid": "2.1.2.2.3",           "name": "Shuli (Bendheim) Steinlauf", "alt": "Shulamit Yael (Bendheim) Steinlauf"},
    {"pid": "2.1.2.2.3S",          "name": "Avi Steinlauf", "alt": "Avraham Steinlauf"},
    {"pid": "2.1.2.2.3.1",         "name": "Elli (Steinlauf) Miller", "alt": "Eliana Esther Steinlauf"},
    {"pid": "2.1.2.2.3.1S",        "name": "Nathan Miller"},
    {"pid": "2.1.2.2.3.2",         "name": "Gavriel Steinlauf"},
    {"pid": "2.1.2.2.3.3",         "name": "Noam Steinlauf"},
    {"pid": "2.1.2.2.3.4",         "name": "Meital Steinlauf"},
    {"pid": "2.1.2.2.3.5",         "name": "Amalia Steinlauf"},
    {"pid": "2.1.2.2.3.6",         "name": "Oren Steinlauf"},
    {"pid": "2.1.2.2.4",           "name": "Yonatan Bendheim", "alt": "Jonathan Meshulam Bendheim"},
    {"pid": "2.1.2.2.4S",          "name": "Esther (Feingold) Bendheim"},
    {"pid": "2.1.2.2.4.1",         "name": "Akiva Bendheim", "alt": "Akiva Mendel Bendheim"},
    {"pid": "2.1.2.2.4.2",         "name": "Avigail Bendheim", "alt": "Abigail Leba Bendheim"},
    {"pid": "2.1.2.2.4.3",         "name": "Ruth Bendheim"},
    {"pid": "2.1.2.2.4.4",         "name": "Miriam Bendheim"},
    {"pid": "2.1.2.2.4.5",         "name": "Yael Bendheim"},
    {"pid": "2.1.2.2.5",           "name": "Tamar (Bendheim) Zakheim", "alt": "Tamar Elisheva Bendheim"},
    {"pid": "2.1.2.2.5S",          "name": "Reuven Zakheim"},
    {"pid": "2.1.2.2.5.1",         "name": "Ma'ayan Zakheim"},
    {"pid": "2.1.2.2.5.2",         "name": "Keira Zakheim"},
    {"pid": "2.1.2.2.5.3",         "name": "Rimonne Zakheim"},
    {"pid": "2.1.2.2.5.4",         "name": "Danya Zakheim"},
    {"pid": "2.1.2.2.5.5",         "name": "David Maccabee 'Mac' Zakheim"},
    {"pid": "2.1.2.2.6",           "name": "Etan Bendheim", "alt": "Ethan Yitzchak Bendheim"},
    {"pid": "2.1.2.2.6S",          "name": "Sarah (Roer) Bendheim"},
    {"pid": "2.1.2.2.6.1",         "name": "Le'eila Bendheim"},
    {"pid": "2.1.2.2.6.2",         "name": "Dassi Bendheim"},
    {"pid": "2.1.2.2.6.3",         "name": "Kiva/Baruch Bendheim"},
    {"pid": "2.1.2.2.6.4",         "name": "Charlie Bendheim"},
    {"pid": "2.1.2.2.6.5",         "name": "Ayala Yehudit (Judith Ayala) Bendheim"},
    {"pid": "2.1.2.2.6.6",         "name": "Dahlia Genendel (Dahlia Karoline) Bendheim"},
    {"pid": "2.1.2.2.7",           "name": "Gilad Bendheim", "alt": "Gilad Yair Bendheim"},
    {"pid": "2.1.2.2.7S",          "name": "Tzippy (Quint) Bendheim"},
    {"pid": "2.1.2.2.7.1",         "name": "Netanel Yehuda Bendheim"},
    {"pid": "2.1.2.2.7.2",         "name": "Gavriel Dovid Bendheim"},
    {"pid": "2.1.2.2.7.3",         "name": "Asher Binyamin Bendheim"},
    {"pid": "2.1.2.2.7.4",         "name": "Liana Rivka Bendheim"},
    {"pid": "2.1.2.3",             "name": "Debbie Eisenberg", "alt": "Debra Gill (Bendheim) Eisenberg"},
    {"pid": "2.1.2.3S",            "name": "Barry Eisenberg", "alt": "Barry Lev Eisenberg"},
    {"pid": "2.1.2.3.1",           "name": "Michael Eisenberg", "alt": "Michael Aaron Eisenberg"},
    {"pid": "2.1.2.3.1S",          "name": "Yaffa (Knecht) Eisenberg", "alt": "Yaffa Malka (Knecht) Eisenberg"},
    {"pid": "2.1.2.3.1.1",         "name": "Tamar Abramson", "alt": "Tamar Nechama Eisenberg"},
    {"pid": "2.1.2.3.1.1S",        "name": "Yosef Abramson"},
    {"pid": "2.1.2.3.1.1.1",       "name": "Anaelle Abramson"},
    {"pid": "2.1.2.3.1.1.2",       "name": "Mayan Hallel Abramson"},
    {"pid": "2.1.2.3.1.1.3",       "name": "Eitan Refael Abramson"},
    {"pid": "2.1.2.3.1.1.4",       "name": "Noa Rachel Abramson"},
    {"pid": "2.1.2.3.1.2",         "name": "Sonny Eisenberg", "alt": "Isaiah Jacob Eisenberg"},
    {"pid": "2.1.2.3.1.2S",        "name": "Sagit (Shloush) Eisenberg"},
    {"pid": "2.1.2.3.1.2.1",       "name": "Or Chaim Eisenberg"},
    {"pid": "2.1.2.3.1.2.2",       "name": "Eden Rachel Eisenberg"},
    {"pid": "2.1.2.3.1.3",         "name": "Chaim Eisenberg", "alt": "Charlie Eisenberg"},
    {"pid": "2.1.2.3.1.3S",        "name": "Gabby (Jacobson) Eisenberg"},
    {"pid": "2.1.2.3.1.3.1",       "name": "Eliora Rachel Eisenberg"},
    {"pid": "2.1.2.3.1.3.2",       "name": "Ariel David Eisenberg"},
    {"pid": "2.1.2.3.1.4",         "name": "Sara (Eisenberg) Gelertner", "alt": "Sara Freida Eisenberg"},
    {"pid": "2.1.2.3.1.4S",        "name": "Yaacov Gelertner"},
    {"pid": "2.1.2.3.1.4.1",       "name": "Neta Tova Gelertner"},
    {"pid": "2.1.2.3.1.4.2",       "name": "David Natan Gelertner"},
    {"pid": "2.1.2.3.1.5",         "name": "Yehuda Eisenberg"},
    {"pid": "2.1.2.3.1.5S",        "name": "Hadar (Chasid) Eisenberg"},
    {"pid": "2.1.2.3.1.6",         "name": "Moshe Eisenberg"},
    {"pid": "2.1.2.3.1.7",         "name": "Bat-Sheva Eisenberg"},
    {"pid": "2.1.2.3.1.8",         "name": "Nili Eisenberg"},
    {"pid": "2.1.2.3.2",           "name": "Shafrira (Eisenberg) Wiener", "alt": "Shafrira Nannette (Eisenberg) Wiener"},
    {"pid": "2.1.2.3.2S",          "name": "Ben Wiener", "alt": "Benjamin Wiener"},
    {"pid": "2.1.2.3.2.1",         "name": "Aliza (Wiener) Wimpfheimer", "alt": "Aliza Wiener"},
    {"pid": "2.1.2.3.2.1S",        "name": "Yair Wimpfheimer"},
    {"pid": "2.1.2.3.2.1.1",       "name": "Itiel Wimpfheimer"},
    {"pid": "2.1.2.3.2.1.2",       "name": "Tzuri Elyashiv Wimpfheimer"},
    {"pid": "2.1.2.3.2.1.3",       "name": "Matanya Levi Wimpfheimer"},
    {"pid": "2.1.2.3.2.2",         "name": "Ariella (Wiener) Meyer", "alt": "Ariella Wiener"},
    {"pid": "2.1.2.3.2.2S",        "name": "Simcha Meyer"},
    {"pid": "2.1.2.3.2.2.1",       "name": "Lia Shayna Meyer"},
    {"pid": "2.1.2.3.2.2.2",       "name": "Maayan Netanel Meyer"},
    {"pid": "2.1.2.3.2.2.3",       "name": "Ellie Tzipora Meyer"},
    {"pid": "2.1.2.3.2.3",         "name": "Ora (Wiener) Turitz", "alt": "Ora Wiener"},
    {"pid": "2.1.2.3.2.3S",        "name": "Elan Zev Turitz"},
    {"pid": "2.1.2.3.2.3.1",       "name": "Shirley Hadassah Turitz"},
    {"pid": "2.1.2.3.2.3.2",       "name": "Amichai Dror Turitz"},
    {"pid": "2.1.2.3.2.3.3",       "name": "Adielle Dodi Turitz"},
    {"pid": "2.1.2.3.2.4",         "name": "Sruli Wiener", "alt": "Yisroel Yitzchak Wiener"},
    {"pid": "2.1.2.3.2.5",         "name": "Gabriella (Wiener) Sheets"},
    {"pid": "2.1.2.3.2.5S",        "name": "Ariel Sheets"},
    {"pid": "2.1.2.3.2.6",         "name": "Shai Wiener"},
    {"pid": "2.1.2.3.2.7",         "name": "Amalia Wiener"},
    {"pid": "2.1.2.3.3",           "name": "Noam Eisenberg", "alt": "Noam Yitzchak Eisenberg"},
    {"pid": "2.1.2.3.3S",          "name": "Shana (Melamed) Eisenberg", "alt": "Shana Eisenberg"},
    {"pid": "2.1.2.3.3.1",         "name": "Tzippi (Eisenberg) Wieder", "alt": "Sara Tzippora Eisenberg"},
    {"pid": "2.1.2.3.3.1S",        "name": "Noam Wieder"},
    {"pid": "2.1.2.3.3.2",         "name": "Kira Eisenberg", "alt": "Yakira \"Kira\" Eisenberg"},
    {"pid": "2.1.2.3.3.3",         "name": "Moriah Eisenberg"},
    {"pid": "2.1.2.3.3.4",         "name": "Yael Eisenberg"},
    {"pid": "2.1.2.3.3.5",         "name": "Ezra Eisenberg"},
    {"pid": "2.1.2.3.4",           "name": "Miriam (Eisenberg) Mark", "alt": "Miriam Fredda (Eisenberg) Mark"},
    {"pid": "2.1.2.3.4S",          "name": "Ari Mark"},
    {"pid": "2.1.2.3.4.1",         "name": "Yonatan Mark"},
    {"pid": "2.1.2.3.4.2",         "name": "Raphi Mark"},
    {"pid": "2.1.2.3.4.3",         "name": "Dalia Mark"},
    {"pid": "2.1.2.3.4.4",         "name": "Annie Mark"},
    {"pid": "2.1.2.3.5",           "name": "Deena (Eisenberg) Pulitzer", "alt": "Deena Fayge Eisenberg"},
    {"pid": "2.1.2.3.5S",          "name": "Jonathan Pulitzer"},
    {"pid": "2.1.2.3.5.1",         "name": "Daniella Pulitzer"},
    {"pid": "2.1.2.3.5.2",         "name": "Liana Pulitzer"},
    {"pid": "2.1.2.3.5.3",         "name": "David Pulitzer"},
    {"pid": "2.1.2.3.5.4",         "name": "Maya Shay Pulitzer"},
    {"pid": "2.1.2.3.6",           "name": "Elisheva (Eisenberg) Goldman", "alt": "Elisheva Sophie Eisenberg"},
    {"pid": "2.1.2.3.6S",          "name": "Ephraim Goldman"},
    {"pid": "2.1.2.3.6.1",         "name": "Talya Goldman"},
    {"pid": "2.1.2.3.6.2",         "name": "Itai Goldman"},
    {"pid": "2.1.2.3.6.3",         "name": "Shaya Goldman"},
    {"pid": "2.1.2.3.6.4",         "name": "Natan Goldman"},
    {"pid": "2.1.2.3.6.5",         "name": "Aviad Goldman"},
    {"pid": "2.1.2.3.7",           "name": "Daphne (Eisenberg) Cohen", "alt": "Daphne Shira Eisenberg"},
    {"pid": "2.1.2.3.7S",          "name": "Daniel Cohen"},
    {"pid": "2.1.2.3.7.1",         "name": "Mordechai Cohen"},
    {"pid": "2.1.2.3.7.2",         "name": "Tal Cohen"},
    {"pid": "2.1.2.3.7.3",         "name": "Geffen Cohen"},
    {"pid": "2.1.2.3.7.4",         "name": "Eitan Cohen"},
    {"pid": "2.1.2.3.7.5",         "name": "Harel Cohen"},
    {"pid": "2.1.2.4",             "name": "Aviva Sussman", "alt": "Aviva B. (Bendheim) Sussman"},
    {"pid": "2.1.2.4S",            "name": "Marvin Sussman", "alt": "Marvin Stuart Sussman"},
    {"pid": "2.1.2.4.1",           "name": "Avi Sussman", "alt": "Elliott Ivan Sussman"},
    {"pid": "2.1.2.4.1S",          "name": "Rina (Hain) Sussman", "alt": "Rina Beth (Hain) Sussman"},
    {"pid": "2.1.2.4.1.1",         "name": "Yael (Sussman) Merlin", "alt": "Yael Michal Sussman"},
    {"pid": "2.1.2.4.1.1S",        "name": "Ohad Merlin"},
    {"pid": "2.1.2.4.1.1.1",       "name": "Harel Gil Merlin"},
    {"pid": "2.1.2.4.1.1.2",       "name": "Nevo Omer Merlin"},
    {"pid": "2.1.2.4.1.1.3",       "name": "Yuval Matanel Merlin"},
    {"pid": "2.1.2.4.1.2",         "name": "Lital (Sussman) Hadad", "alt": "Lital Helen Sussman"},
    {"pid": "2.1.2.4.1.2S",        "name": "Snir Hadad"},
    {"pid": "2.1.2.4.1.2.1",       "name": "Niv Ariel Hadad"},
    {"pid": "2.1.2.4.1.3",         "name": "Yoav Sussman"},
    {"pid": "2.1.2.4.1.4",         "name": "Itai Sussman"},
    {"pid": "2.1.2.4.2",           "name": "JJ Sussman", "alt": "Joseph Jay Sussman"},
    {"pid": "2.1.2.4.2S",          "name": "Aliza (Kravetz) Sussman"},
    {"pid": "2.1.2.4.2.1",         "name": "Shira Sussman", "alt": "Shira Ethel Sussman"},
    {"pid": "2.1.2.4.2.2",         "name": "Abie Sussman", "alt": "Avraham \"Abie\" Sussman"},
    {"pid": "2.1.2.4.2.3",         "name": "Yair Sussman", "alt": "Yair Shalom Sussman"},
    {"pid": "2.1.2.4.2.4",         "name": "Chaim Sussman"},
    {"pid": "2.1.2.4.2.5",         "name": "Yitzchak Sussman"},
    {"pid": "2.1.2.4.2.6",         "name": "Ariel Sussman"},
    {"pid": "2.1.2.4.3",           "name": "Eric Sussman", "alt": "Eric Mark Sussman"},
    {"pid": "2.1.2.4.3S",          "name": "Dalia (Furst) Sussman"},
    {"pid": "2.1.2.4.3.1",         "name": "Rebecca Sussman"},
    {"pid": "2.1.2.4.3.2",         "name": "Ethan Sussman"},
    {"pid": "2.1.2.4.3.3",         "name": "Julia Sussman"},
    {"pid": "2.1.2.4.4",           "name": "Amanda (Sussman) Katz", "alt": "Amanda M. (Sussman) Katz"},
    {"pid": "2.1.2.4.4S",          "name": "Meir Katz"},
    {"pid": "2.1.2.4.4.1",         "name": "Chai Katz"},
    {"pid": "2.1.2.4.4.2",         "name": "Ayla Katz"},
    {"pid": "2.1.2.4.4.3",         "name": "Meirav Katz"},
    {"pid": "2.1.2.4.5",           "name": "Shari (Sussman) Goldberg", "alt": "Shari S. Sussman"},
    {"pid": "2.1.2.4.5.1",         "name": "Evelyn Goldberg"},
    {"pid": "2.1.2.4.5.2",         "name": "Phillip Goldberg"},
    {"pid": "2.1.2.4.6",           "name": "Ilana (Sussman) Uretsky", "alt": "Elizabeth I. Sussman"},
    {"pid": "2.1.2.4.6S",          "name": "Jon Uretsky"},
    {"pid": "2.1.2.4.6.1",         "name": "Charley Uretsky"},
    {"pid": "2.1.2.4.6.2",         "name": "Amelia Lev Uretsky"},
    {"pid": "2.1.2.4.6.3",         "name": "Noah Zion Uretsky"},
    {"pid": "2.1.2.4.6.4",         "name": "Eli Solomon Uretsky"},
    {"pid": "2.1.2.5",             "name": "Philip Bendheim", "alt": "Philip Eliezer Lipman Bendheim"},
    {"pid": "2.1.2.5S",            "name": "Donna (Hirschfeld) Bendheim", "alt": "Donna Lynn (Hirschfeld) Bendheim"},
    {"pid": "2.1.2.5.1",           "name": "Sharonne (Bendheim) Turen", "alt": "Sharonne Abigail (Bendheim) Turen"},
    {"pid": "2.1.2.5.1S",          "name": "Tzachi Turen", "alt": "Itzchak Aron Turen"},
    {"pid": "2.1.2.5.1.1",         "name": "Charlie Turen", "alt": "Charles Henry Turen"},
    {"pid": "2.1.2.5.1.2",         "name": "Evie (Turen) Wolf", "alt": "Eva Rachel Turen"},
    {"pid": "2.1.2.5.1.2S",        "name": "Binyamin Wolf"},
    {"pid": "2.1.2.5.1.3",         "name": "Mia Turen", "alt": "Mia Stella Turen"},
    {"pid": "2.1.2.5.1.4",         "name": "Ella Turen", "alt": "Ella Elizabeth Turen"},
    {"pid": "2.1.2.5.1.5",         "name": "Jack Turen", "alt": "Jack William Turen"},
    {"pid": "2.1.2.5.2",           "name": "Ephraim Bendheim", "alt": "Jeremy Ephraim Bendheim"},
    {"pid": "2.1.2.5.2S",          "name": "Leale (Kraus) Bendheim", "alt": "Leah Leale (Kraus) Bendheim"},
    {"pid": "2.1.2.5.2.1",         "name": "Shoshi (Bendheim) Finkel", "alt": "Shoshana Rachel Bendheim"},
    {"pid": "2.1.2.5.2.1S",        "name": "Meir Finkel"},
    {"pid": "2.1.2.5.2.1.1",       "name": "David Finkel"},
    {"pid": "2.1.2.5.2.1.2",       "name": "Rivka Finkel"},
    {"pid": "2.1.2.5.2.1.3",       "name": "Sara Ita Finkel"},
    {"pid": "2.1.2.5.2.2",         "name": "Avigayil (Bendheim) Prinz", "alt": "Avigayil Bendheim"},
    {"pid": "2.1.2.5.2.2S",        "name": "Shloimy Prinz"},
    {"pid": "2.1.2.5.2.2.1",       "name": "Michael Prinz"},
    {"pid": "2.1.2.5.2.3",         "name": "Yaeli (Bendheim) Farbstein", "alt": "Yael Bendheim"},
    {"pid": "2.1.2.5.2.3S",        "name": "Avreimi Farbstein"},
    {"pid": "2.1.2.5.2.4",         "name": "Chani Bendheim", "alt": "Peesyl Chani Bendheim"},
    {"pid": "2.1.2.5.2.5",         "name": "Chaim Bendheim"},
    {"pid": "2.1.2.5.2.6",         "name": "Akiva Bendheim"},
    {"pid": "2.1.2.5.2.7",         "name": "Tamar Bendheim"},
    {"pid": "2.1.2.5.2.8",         "name": "Avraham Bendheim", "alt": "Abraham Gedalia Bendheim"},
    {"pid": "2.1.2.5.2.9",         "name": "Yaakov Bendheim"},
    {"pid": "2.1.2.5.2.10",        "name": "David Bendheim"},
    {"pid": "2.1.2.5.2.11",        "name": "Daniel Bendheim"},
    {"pid": "2.1.2.5.3",           "name": "Ayelet (Bendheim) Raab", "alt": "Ayelet Nurit (Bendheim) Raab"},
    {"pid": "2.1.2.5.3S",          "name": "Yitz Raab", "alt": "Yitzchak Raab"},
    {"pid": "2.1.2.5.3.1",         "name": "Ruthie Raab", "alt": "Rivka Ruth Raab"},
    {"pid": "2.1.2.5.3.2",         "name": "Eden (Raab) Tarshish", "alt": "Eden Ariella Raab"},
    {"pid": "2.1.2.5.3.2S",        "name": "Gabi Tarshish", "alt": "Gabriel Tarsis"},
    {"pid": "2.1.2.5.3.3",         "name": "Shlomo Raab", "alt": "Shlomo Chaim Raab"},
    {"pid": "2.1.2.5.3.4",         "name": "Boaz Raab", "alt": "Boaz Ephraim Raab"},
    {"pid": "2.1.2.5.4",           "name": "Efrat (Bendheim) Ziering", "alt": "Efrat Leorre (Bendheim) Ziering"},
    {"pid": "2.1.2.5.4S",          "name": "David Ziering", "alt": "David Ephraim Ziering"},
    {"pid": "2.1.2.5.4.1",         "name": "Gila (Ziering) Shizgal", "alt": "Gila Zlota Ziering"},
    {"pid": "2.1.2.5.4.1S",        "name": "Pinchas Shizgal"},
    {"pid": "2.1.2.5.4.2",         "name": "Yechiel Ziering", "alt": "Yechiel Michel Ziering"},
    {"pid": "2.1.2.5.4.3",         "name": "Chaim Ziering", "alt": "Chaim Yosef Ziering"},
    {"pid": "2.1.2.5.4.4",         "name": "Emuna Ziering", "alt": "Emunah Rachel Ziering"},
    {"pid": "2.1.2.5.4.5",         "name": "Moshe Ziering", "alt": "Moshe Aaron Ziering"},
    {"pid": "2.1.2.5.4.6",         "name": "Yehuda Ziering", "alt": "Yehuda Yechezkel Shraga Ziering"},
    {"pid": "2.1.2.5.4.7",         "name": "Zechariah Simcha Ziering"},
    {"pid": "2.1.2.5.4.8",         "name": "Maayan Shira Ziering"},
    {"pid": "2.1.2.5.5",           "name": "Nina Bendheim", "alt": "Nina Shifra Bendheim"},
    {"pid": "2.1.2.5.6",           "name": "Avner/Chezki Bendheim", "alt": "Avner Yechezkel Bendheim"},
    {"pid": "2.1.2.5.6S",          "name": "Tamar (Rohatiner) Bendheim", "alt": "Tamar Rohatiner"},
    {"pid": "2.1.2.5.6.1",         "name": "Manny (Emanuel) Bendheim", "alt": "Emanuel Chaim \"Manny\" Bendheim"},
    {"pid": "2.1.2.5.6.2",         "name": "Eddie Bendheim"},
    {"pid": "2.1.2.5.6.3",         "name": "Gerri Bendheim", "alt": "Gerri Rachel Bendheim"},
    {"pid": "2.1.2.5.6.4",         "name": "Sandi Bendheim"},
    {"pid": "2.1.2.5.6.5",         "name": "Re'i Chai Bendheim"},
    {"pid": "2.1.2.5.7",           "name": "Gavi Bendheim", "alt": "Gavriel Ivan Bendheim"},
    {"pid": "2.1.2.5.7S",          "name": "Hadas (Tzur) Bendheim", "alt": "Hadas Tzur"},
    {"pid": "2.1.2.5.7.1",         "name": "Jonah David Bendheim", "alt": "Yona David Bendheim"},
    {"pid": "2.1.2.5.7.2",         "name": "Carmi Rivka Bendheim"},
    {"pid": "2.1.2.6",             "name": "Edna Zussman", "alt": "Edna Esther (Bendheim) Zussman"},
    {"pid": "2.1.2.6S",            "name": "Aver Zussman", "alt": "Aver Yizchak Zussman"},
    {"pid": "2.1.2.6.1",           "name": "Nannette (Zussman) Fox", "alt": "Nannette Sophie (Zussman) Fox"},
    {"pid": "2.1.2.6.1S",          "name": "Matt Fox", "alt": "Matt Ari Fox"},
    {"pid": "2.1.2.6.1.1",         "name": "Shalhevet Fox"},
    {"pid": "2.1.2.6.1.2",         "name": "Emanuel Fox", "alt": "Imanuel Fox"},
    {"pid": "2.1.2.6.1.2S",        "name": "Shulamit (Shiloni) Fox"},
    {"pid": "2.1.2.6.1.3",         "name": "Aviad Fox"},
    {"pid": "2.1.2.6.1.4",         "name": "Elisha Fox"},
    {"pid": "2.1.2.6.1.5",         "name": "Leora Fox"},
    {"pid": "2.1.2.6.2",           "name": "Tzvi Zussman"},
    {"pid": "2.1.2.6.2S",          "name": "Sarit (Rosenbaum) Zussman", "alt": "Sarit (Rosenboim) Zussman"},
    {"pid": "2.1.2.6.2.1",         "name": "Ben Zussman"},
    {"pid": "2.1.2.6.2.2",         "name": "Mika Zussman"},
    {"pid": "2.1.2.6.2.3",         "name": "Boaz Zussman"},
    {"pid": "2.1.2.6.3",           "name": "Sophie (Zussman) Belisha", "alt": "Sophie Wilhemina Shifra Zussman"},
    {"pid": "2.1.2.6.3S",          "name": "Itamar Belisha"},
    {"pid": "2.1.2.6.3.1",         "name": "Galia Belisha"},
    {"pid": "2.1.2.6.3.2",         "name": "Aiden Cochava Belisha"},
    {"pid": "2.1.2.6.4",           "name": "Sara (Zussman) Tobolsky", "alt": "Sara Frayda Zussman"},
    {"pid": "2.1.2.6.4S",          "name": "Moishi Tobolsky"},
    {"pid": "2.1.2.6.4.1",         "name": "Yonatan Tobolsky"},
    {"pid": "2.1.2.6.4.2",         "name": "Avigail Tobolsky"},
    {"pid": "2.1.2.6.4.3",         "name": "Yehuda Tobolsky"},
    {"pid": "2.1.2.6.4.4",         "name": "Michal Tobolsky"},
    {"pid": "2.1.2.6.4.5",         "name": "Hagai Tobolsky"},
    {"pid": "2.1.2.6.4.6",         "name": "Avraham Tobolsky"},
    {"pid": "2.1.2.6.4.7",         "name": "Efrat Tobolsky"},
    {"pid": "2.1.2.6.5",           "name": "Meshulam Zussman", "alt": "Meshulam Asher Zussman"},
    {"pid": "2.1.2.6.5S",          "name": "Talor (Goldvicht) Zussman", "alt": "Talor Miriam (Family name unknown)"},
    {"pid": "2.1.2.6.5.1",         "name": "Yedaya Zussman", "alt": "Yedaya Chaim \"Charlie\" Zussman"},
    {"pid": "2.1.2.6.5.2",         "name": "Elroi Zussman", "alt": "Elroi David Zussman"},
    {"pid": "2.1.2.6.5.3",         "name": "Yonadav Zussman", "alt": "Yonadav Binyamin Zussman"},
    {"pid": "2.1.2.6.5.4",         "name": "Tagel Tzion Yehudit Zussman", "alt": "Tagel Tzion Zussman"},
    {"pid": "2.1.2.6.5.5",         "name": "Achiam Pinchas Zussman"},
    {"pid": "2.1.2.6.6",           "name": "Tzipora (Zussman) Dinnen", "alt": "Tzipora Ivanne Zussman"},
    {"pid": "2.1.2.6.6S",          "name": "Yossi Dinnen"},
    {"pid": "2.1.2.6.6.1",         "name": "Merav Dinnen"},
    {"pid": "2.1.2.6.6.2",         "name": "Ellie Dinnen"},
    {"pid": "2.1.2.6.6.3",         "name": "אוריה חיה Dinnen"},
    {"pid": "2.1.2.6.6.4",         "name": "ליבי בנימינה Dinnen"},
    {"pid": "2.1.2.6.7",           "name": "Liat (Zussman) Cannah", "alt": "Liat Bat-Sheva Zussman"},
    {"pid": "2.1.2.6.7S",          "name": "Dudu Cannah"},
    {"pid": "2.1.2.6.7.1",         "name": "Charlie Shaili Achinoam Cannah"},
    {"pid": "2.1.2.6.7.2",         "name": "Tohm Bettie Refael Cannah"},
    {"pid": "2.1.2.6.7.3",         "name": "Bar Tzion Blumah Cannah"},
    {"pid": "2.1.2.6.8",           "name": "Avishai Zussman", "alt": "Avishai Avraham Shai Zussman"},
    {"pid": "2.1.2.6.8S",          "name": "Rebecca (Fuchs) Zussman"},
    {"pid": "2.1.2.6.8.1",         "name": "Yael Zussman"},
    {"pid": "2.1.2.6.8.2",         "name": "Amichai Zussman"},
    {"pid": "2.1.2.6.8.3",         "name": "Shachar Zussman"},
    {"pid": "2.1.2.6.8.4",         "name": "Lev Zussman"},
    {"pid": "2.1.2.6.8.5",         "name": "Beeri Nitzan Zussman"},
    {"pid": "2.1.2.7",             "name": "Karen Levine", "alt": "Karen Shulamit (Bendheim) Levine"},
    {"pid": "2.1.2.7S",            "name": "Billy Levine", "alt": "William Zev Levine"},
    {"pid": "2.1.2.7.1",           "name": "Renana (Levine) Pashkus", "alt": "Renana Levine"},
    {"pid": "2.1.2.7.1S",          "name": "Itzik Pashkus"},
    {"pid": "2.1.2.7.1.1",         "name": "Hallel Aliza Pashkus"},
    {"pid": "2.1.2.7.1.2",         "name": "Noam Esther Pashkus"},
    {"pid": "2.1.2.7.1.3",         "name": "Oriel Akiva Pashkus"},
    {"pid": "2.1.2.7.2",           "name": "Tali (Levine) Friedman", "alt": "Avital \"Tali\" Levine"},
    {"pid": "2.1.2.7.2S",          "name": "Roi Friedman"},
    {"pid": "2.1.2.7.2.1",         "name": "Yahav Friedman"},
    {"pid": "2.1.2.7.2.2",         "name": "Yarden Charlie Friedman"},
    {"pid": "2.1.2.7.3",           "name": "Naama (Levine) Kramer", "alt": "Naama Levine"},
    {"pid": "2.1.2.7.3S",          "name": "Ilan Dobuler"},
    {"pid": "2.1.2.7.3.1",         "name": "Eden Kramer"},
    {"pid": "2.1.2.7.3.2",         "name": "Yotam Kramer"},
    {"pid": "2.1.2.7.3.3",         "name": "Ye'ela Kramer"},
    {"pid": "2.1.2.7.4",           "name": "Netta (Levine) Ben Ichay", "alt": "Netta Levine"},
    {"pid": "2.1.2.7.4S",          "name": "Chanan Ben Ichay"},
    {"pid": "2.1.2.7.4.1",         "name": "Malachi Ben Ichay"},
    {"pid": "2.1.2.7.4.2",         "name": "Nitzan Ben Ichay"},
    {"pid": "2.1.2.7.4.3",         "name": "Tal Ben Ichay"},
    {"pid": "2.1.2.7.4.4",         "name": "Naomi Shlomit Ben Ichay"},
    {"pid": "2.1.2.7.4.5",         "name": "David Ehud Ben Ichay"},
    {"pid": "2.1.2.7.4.6",         "name": "Hod Esther Ben Ichay"},
    {"pid": "2.1.2.7.4.7",         "name": "Yehoshua Ben Ichay"},
    {"pid": "2.1.2.7.4.8",         "name": "Shilo Yoav Ben Ichay"},
    {"pid": "2.1.2.7.5",           "name": "Aharon Levine"},
    {"pid": "2.1.2.7.5S",          "name": "Hila (Weksler) Levine"},
    {"pid": "2.1.2.7.5.1",         "name": "Ella Mia Levine"},
    {"pid": "2.1.2.7.5.2",         "name": "Ori Shalom Levine"},
    {"pid": "2.1.2.7.5.3",         "name": "Ariel Lia Levine"},
    {"pid": "2.1.2.7.5.4",         "name": "Aderet Levine"},
    {"pid": "2.1.2.7.6",           "name": "Yair Levine"},
    {"pid": "2.1.2.7.6S",          "name": "Moriah (Pollack) Levine"},
    {"pid": "2.1.2.7.6.1",         "name": "Beeri Baruch Levine"},
    {"pid": "2.1.2.7.6.2",         "name": "Noga Aliza Levine"},
    {"pid": "2.1.2.7.6.3",         "name": "Aviv Els Levine"}
  ]
};
